### PR TITLE
[Metrics Explorer] Add configurable explore API to configure runtime in cloud

### PR DESCRIPTION
**Pull request by AdityaHegde**
Added a new component ConfigProvider. Currently takes a config object or an explore url. It creates a RootConfig object with explore url if provided else uses the config object override.

### CODE REVIEW

**Review by ericpgreen2 — CHANGES_REQUESTED** [review]
I think we should be able to drastically simplify this. Instead of setting this config as a context and passing it through to every function, we could set a a global constant `EXPLORE_HOST` and import it into `queries/metrics-view.ts`.

Then `fetchUrl()` can include this line:
```javascript
await fetch(`${EXPLORE_HOST}/api/v1/${path}`
```

In Beneath, we had this [lib/connection.ts](https://github.com/beneath-hq/beneath/blob/master/web/lib/connection.ts) file that was quite handy. We could set the environment in this one place and import the constants throughout the codebase.

**Comment by AdityaHegde** [comment]
Ya that is one option for sure. I was more so using svelte's context to make it agnostic of whether we are in production or not.

Besides the URL will most probably be selected programatically. The runtime URL is assigned to a UI based on various aspects. So a global constant will not work.

**Comment by ericpgreen2** [comment]
> Besides the URL will most probably be selected programatically. The runtime URL is assigned to a UI based on various aspects. So a global constant will not work.

What aspects are dynamic? I'm picturing an environment variable that would fix the config at runtime. Like, this could be the `lib/connection.ts` file:

```
export const IS_CLOUD = process.env.NODE_ENV === "cloud";
export const EXPLORE_HOST = IS_CLOUD ? "rilldata.com" : "localhost:8080";
```

My main concern with the context approach is that passing the host into each of our `svelte-query` hooks assumes the config is dynamic, but I think it's fixed.

**Comment by AdityaHegde** [comment]
I do not want any reference to ENV anywhere. It is not scalable. Say you need a new env to either test or for an internal dashboard we need another check for that specifically. The url will be sent by the go server based on its env config (process.env will not be available in the long run since nodejs server will go away).

Also the runtime instance assigned might be based on projects. So making this dynamic will allow for things like that. @begelundmuller what do you think about this approach?

**Comment by begelundmuller** [comment]
Aditya's right that we'll need to be able to handle dynamic runtime URLs. Unfortunately the runtime won't always be at a predictable URL – for example, we may need to connect to both local and cloud runtimes from the local Rill Developer. Deploying multiple runtimes (say, us-east1.runtime.rilldata.com, etc.) may also be our short-term path to multi-cloud (albeit a little ugly).

As for the general case, I do think ENVs are great for passing in config data, as long as you're disciplined about how you reference them. For automated testing, you can parse them into config objects (that you inject into dependencies) that can easily be configured differently for test cases. (Being mindful that for a SPA, env vars are really build-time config, not values that are actually dynamic at runtime).

**Review by ericpgreen2 — APPROVED** [review]

**Comment by ericpgreen2** [comment]
I stand corrected :)

Approved so you can merge after fixing the merge conflicts.

**Pull request merged**
