### PR TITLE
Move static assets to `web-common`

### PR DESCRIPTION
**Pull request by ericpgreen2**
For `web-admin` to leverage our static assets (currently, our fonts & favicon), I've moved them from `web-local/static` into `web-common/static` and configured our SvelteKit projects, `web-local` and `web-admin`, to read the `web-common/static` directory.

I looked into keeping `robots.txt` in a separate `web-admin/static` folder, but [SvelteKit does not yet support multiple static directories](https://github.com/sveltejs/kit/issues/5115).

Part of #1780.

### CODE REVIEW

**Review by begelundmuller — COMMENTED** [review]
Can it still also have local and admin specific assets as well? It would be nice to be able to decouple those.

Also, just another question, is there an NPM package for Inter that we could use so we don't need to copy them into the repo?

**Review by begelundmuller — APPROVED** [review]
Approving since my questions above can be resolved later if necessary. This looks good

**Comment by ericpgreen2** [comment]
Moving my Slack question to @hamilton here –

Thoughts on Benjamin's fonts idea? I found [this Inter NPM package](https://www.npmjs.com/package/@fontsource/inter), but haven't found anything yet for MD IO.

**Comment by ericpgreen2** [comment]
> Thoughts on Benjamin's fonts idea? I found [this Inter NPM package](https://www.npmjs.com/package/@fontsource/inter), but haven't found anything yet for MD IO.

@hamilton mentioned that we're using the "tabular numbers" OpenType feature. I found that fontsource has [quite limited OpenType support](https://github.com/fontsource/fontsource/issues/39) and [does not offer tabular numbers](https://github.com/fontsource/fontsource/issues/59).

I think I'll leave the Inter files in the repo and we can continue this research another time. Another idea is to [use the Inter distribution](https://rsms.me/inter/#usage) on [Cloudflare's CDN](https://rsms.me/inter/#faq-cdn).

**Comment by ericpgreen2** [comment]
> Can it still also have local and admin specific assets as well? It would be nice to be able to decouple those.

Maybe there's a creative workaround, but otherwise not until [this SvelteKit issue](https://github.com/sveltejs/kit/issues/5115) is solved.

Given we still have the fonts in the repository (see comment above), we can either:
1. decouple local and admin assets & duplicate fonts
2. couple local and admin assets & not duplicate fonts

I feel option 2 (current approach) is best until we get the fonts out of the repo.

@begelundmuller thoughts or merge?

**Comment by begelundmuller** [comment]
Makes sense – let's do the current approach until the fonts are removed. Merge!

**Pull request merged**
