### PR TITLE
Handling spaces in project folder

### LINKED ISSUE #928: Crash when running in directory with space in it
```
/tmp ❯ mkdir "test dir"
/tmp ❯ cd "test dir"
/tmp/test dir ❯ rill init-example
Initializing the example project /private/tmp/test dir/rill-developer-example ...
Directory /private/tmp/test dir/rill-developer-example doesn't exist. Creating the directory.

You have successfully initialized a new project with Rill Developer.

This application is extremely alpha and we want to hear from you if you have any questions or ideas to share! You can reach us in our Rill Discord server at https://bit.ly/3NSMKdT.
Downloading dataset for example project...
Error: Command failed: curl -s http://pkg.rilldata.com/rill-developer-example/example-assets-0.6.zip --output /private/tmp/test dir/rill-developer-example/example-assets-0.6.zip
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at ExampleProjectCommand.createExampleProject (/snapshot/rill-developer/dist/cli/ExampleProjectCommand.js) {
  status: 6,
  signal: null,
  output: [ null, null, null ],
  pid: 85852,
  stdout: null,
  stderr: null
}
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 0.10

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #928

### CODE REVIEW

**Comment by ericpgreen2** [comment]
I'm running into this error when I run `npm run cli -- init-example` from the repo's top-level:
image

Looks like it's a bug with quotation marks.

**Comment by ericpgreen2** [comment]
Hitting an error when I use a directory with a space in it. Again, running `npm run cli -- init-example` from the top-level:

image

**Comment by AdityaHegde** [comment]
Did you pull the latest changes by running `git pull origin spaces-in-folder` ? I cannot reproduce the issue after my fix.

**Comment by AdityaHegde** [comment]
Ah creating a fresh folder and checkout reproduced it. The runtime binary is not installed in the correct path. Moving my existing checkout already had the runtime so didnt run into this 🤦‍♂️

**Comment by ericpgreen2** [comment]
Great, I think we're all set now. Though I'm now finding that our `init-example` script isn't deterministic, and sometimes results in a "Catalogue Error: Table does not exist error", but I'll open that in a separate issue.

**Review by ericpgreen2 — APPROVED** [review]

**Pull request merged**
