### PR TITLE
Make admin server host configurable

### PR DESCRIPTION
**Pull request by ericpgreen2**
This PR sets the admin server URL to be `http://localhost:8080` in development and `https://admin.rilldata.com` in production.

### CODE REVIEW

**Comment by begelundmuller** [comment]
Instead of using the `NODE_ENV`, how about we increase flexibility and make the admin host itself a build variable (`process.env.RILL_ADMIN_HOST`) and just default to `http://localhost:8080` if it's not set? Then we can set `RILL_ADMIN_HOST` as a build env var in Netlify and easily customize it for staging/preview in the future.

**Review by begelundmuller — CHANGES_REQUESTED** [review]
See other comment

**Comment by ericpgreen2** [comment]
Cool, that works.

I prefixed the environment variable with `VITE_` given Vite's documentation here: https://vitejs.dev/guide/env-and-mode.html#env-files

**Review by begelundmuller — APPROVED** [review]
Perfect

**Pull request merged**
