### PR TITLE
Show correct versions in CLI and UI

### PR DESCRIPTION
**Pull request by begelundmuller**
We have two small bugs around version rendering:

- In CLI, running `rill --version` outputs "rill version rill version XXX" (i.e. the prefix is repeated)
- In UI, the version and commit shown in the bottom left corner is not correct

Todo:

- [x] Fix version formatting in CLI for `--version`
- [x] Expose version info over `/local/config` (so it becomes accessible to frontend)
- [x] In frontend, populate version number and commit info from `/local/config` instead of from `package.json` (in bottom left corner AND in telemetry)
- [ ] Version and commit is not available in dev mode anymore. We need to show something meaning full in the UI in this case.

### CODE REVIEW

**Comment by magorlick** [comment]
@begelundmuller , will this also fix our telemetry? The version did not update.

**Comment by begelundmuller** [comment]
> @begelundmuller , will this also fix our telemetry? The version did not update.

Yeah, it will. Telemetry comes from the frontend, where the version was not updated.

**Review by AdityaHegde — APPROVED** [review]

**Comment by begelundmuller** [comment]
@magorlick FYI – in the new release process, version numbers aren't hardcoded in a file, they're only set at release time (when creating the git tag). So when running with `npm run dev` or `make cli`, it will show "built from source" instead of the old version number – and in telemetry where `"is_dev": true`, the version number will be empty.

I'll cut the next release on Tuesday – then before socializing it, I will verify that version numbers are propagated correctly.

**Review by nishantmonu51 — APPROVED** [review]

**Comment by begelundmuller** [comment]
@AdityaHegde, reviewed your edits and they look great! Merging now.

**Pull request merged**
