### PR TITLE
Rename `table` to `source`

### PR DESCRIPTION
**Pull request by ericpgreen2**
Addresses #346.

Note that there are some cases in the code where I keep the "table" terminology – where it specifically refers to database tables and not our semantic user-facing representation.

### CODE REVIEW

**Comment by AdityaHegde** [comment]
We should probably have done this after major PRs are merged. This will be a nightmare to merge with huge PRs like the explore one.

**Comment by ericpgreen2** [comment]
Damn. Well it doesn't make sense for all you with the major PRs outstanding to each have to resolve the merge. So this can wait until those are in `main` and I'll revisit it then.

**Comment by ericpgreen2** [comment]
In the meantime, I can do a much smaller PR to rename the user-facing text, which should be more trivial to merge.

**Comment by ericpgreen2** [comment]
> In the meantime, I can do a much smaller PR to rename the user-facing text, which should be more trivial to merge.

See #415

**Pull request closed without merging**
