### PR TITLE
Make filter toggle include/exclude mode

### LINKED ISSUE #1022: filter pill menu include / exclude logic doesn't match design
Noticing that the semantics around the filter pill menus w/ include + exclude are not what was in the design.

The filter pill menu should have the following behavior:
- when I click on an entry, it should automatically apply that filter to the dashboard. The entry should remain in the menu for the duration of the menu being open so the user has a chance to toggle the filter back on. If this isn't a good idea, I think it'd be good to add back the apply button and use that to explicitly apply.
- the include button on the bottom left of the menu should not be "apply" but instead should switch all the available menu items to whatever it's toggled to.

It appears that the include / exclude button in the menu actually is equivalent to "apply", which isn't quite right here. It needs to toggle the behavior, not serve as an affirmative action.

@magorlick @djbarnwal what do y'all think?

### PR DESCRIPTION
**Pull request by djbarnwal**
closes #1022

### CODE REVIEW

**Comment by djbarnwal** [comment]
@magorlick Can you review the copy for the buttons?

**Comment by hamilton** [comment]
As soon as https://github.com/rilldata/rill-developer/pull/1066 gets merged, I'd be in favor of quickly adding it to this PR & merging.

**Comment by hamilton** [comment]
@djbarnwal is this ready for another check?

**Comment by djbarnwal** [comment]
> @djbarnwal is this ready for another check?

Yes, it's ready for another pass. cc @magorlick

**Review by hamilton — APPROVED** [review]
lgtm, thanks @djbarnwal!

**Pull request merged**
