### PR TITLE
Simplify-assets-sidebar-2

### PR DESCRIPTION
**Pull request by bcolloran**
follow on from #251, removes a prop from CollapsibleTableSummary that is not used in that component and was causing linting errors

### CODE REVIEW

**Comment by bcolloran** [comment]
This is actually a tiny change on top of #251, broke it into a separate PR, not sure if that's better or worse workflow-wise since it compares against main...

**Comment by bcolloran** [comment]
@ericpgreen2 I've tried to keep each of these individual commits small and to explain what I did at each step, so it might be helpful to step through them one at a time to see what I was thinking: https://github.com/rilldata/rill-developer/pull/252/commits

When you look at it all at once compared to `main` it might look like a lot, but it's really not too much per commit.

**Comment by bcolloran** [comment]
(@ericpgreen2 probably obvious, but this assumes #251, so you should wait to review that until this is merged)

**Comment by ericpgreen2** [comment]
It looks like the commits in this PR include the commits in #251. I _think_ we can just close 251 and only merge this one #252 – is that right?

**Comment by ericpgreen2** [comment]
This one looks good to me! Nice cleanups

**Comment by bcolloran** [comment]
> It looks like the commits in this PR include the commits in #251. I _think_ we can just close 251 and only merge this one #252 – is that right?

Yes, that's correct @ericpgreen2.

Thanks for the review! I'll merge :-)

**Pull request merged**
