### PR TITLE
Show leaderboard on narrow screens

### LINKED ISSUE #680: Linechart elements in dashboard push leaderboards out of the window at narrow sizes.
**Describe the bug**
Linechart elements in dashboard push leaderboards out of the window at narrow sizes.

**To Reproduce**
1. Init the example
2. quick start to the dashboard
3. Make sure the left navigation bar is open
4. Change the size of your browser window to a width where the leaderboard is wider than the space between the charts and the right side of the browser window.  This is about 2/3 of the width on most screens.
5. The leaderboard disappears

**Expected behavior**
I expect the last column of leaderboards to stay on the screen where less of the element is seen as the browser widow occludes the right side of the element.

image
image

### PR DESCRIPTION
**Pull request by djbarnwal**
Closes #680

### CODE REVIEW

**Comment by magorlick** [comment]
This is feeling better, much clearer that you aren't missing the leaderboards. Thank you @djbarnwal !

Though improved, there is something about the interaction that feels a little bit strange to me when I can suddenly scroll left-to-right but only for one column when the screen is narrow, but I can always scroll top-to-bottom.  I think that if we presented the scroll bar at the bottom when the option is possible across the elements that are affected it might help me understand what I can do when and why.

**Comment by djbarnwal** [comment]
@magorlick The scroll bar is now visible on X axis now. Also discovered another bug where if you have more measures than it can fit, you couldn't scroll down to see all the line charts. For fixing that have added a scrollbar to the metrics/line-chart section as well depending upon if we have more metrics or not on the page

**Review by hamilton — APPROVED** [review]
nicely done! @magorlick does this work for you? If so, I think we should merge it.

Thanks for catching that other scroll bug too.

**Comment by magorlick** [comment]
This is much improved! Thanks @djbarnwal. Merging.

**Pull request merged**
