### PR TITLE
Prettier on src/routes

### PR DESCRIPTION
**Pull request by bcolloran**
based on proposed config in #190, this it what src/routes looks like when prettified. If we agree on  #190, we can merge this.

### CODE REVIEW

**Comment by bcolloran** [comment]
fyi @AdityaHegde @ericpgreen2 @hamilton  if you want to bikeshed on this...

**Comment by hamilton** [comment]
This should be probably re-done when there are fewer moving parts. Closing for now.

**Comment by hamilton** [comment]
@bcolloran is going to update this PR then we can take another look

**Comment by bcolloran** [comment]
i actually just opened up another: https://github.com/rilldata/rill-developer/pull/223

equally easy to start a new branch off the current main :-)

**Pull request closed without merging**
