### PR TITLE
release notes for 0.9

### PR DESCRIPTION
**Pull request by magorlick**
- [ ] needs validation that everything we are planning to ship will be shipped and merged into the release branch, including these release notes.  This needs to be approved in advance of our release, and merged just in time as we execute the release so they won’t appear in our documentation too early.  @begelundmuller 
- [x] - needs marketing video and still social image hosted on the CDN and links updated in the 0.9 release notes @godzig .  You can find them in [notion](https://www.notion.so/Rill-0-9-Install-Binaries-Filter-Pills-58b369482c4649a284a47a08c633c71c?d=89c329c55ae44545abd8fb12288c20cd#9dae5ff5679a460ea16922e3ae982c78).

### CODE REVIEW

**Comment by godzig** [comment]
@himadrisingh fixed links to binaries in documentation with permalinks to `rill/latest/` in https://github.com/rilldata/rill-developer/commit/8ba8d75a11144f015d7f0412087d27134135070b

- [Link to gif](https://user-images.githubusercontent.com/1851282/186949562-2c954d3a-83a7-46df-9e3e-a585a10045f9.gif) (using gif in github because it's smaller than the mp4)
- [Link to vimeo](https://vimeo.com/743493707)
- [Link to social share image](https://user-images.githubusercontent.com/1851282/186953008-3a551c48-83ef-436e-bf1e-d2a1a805ec7d.jpg)

MD for release notes:
```
image: https://user-images.githubusercontent.com/1851282/186953008-3a551c48-83ef-436e-bf1e-d2a1a805ec7d.jpg
---

![faster-histograms](https://user-images.githubusercontent.com/1851282/186949562-2c954d3a-83a7-46df-9e3e-a585a10045f9.gif "743493707")
```

**Comment by gorillio-ops** [comment]
let me know if we need to change the link convention. We can move away from pkg.rilldata.com and use cdn.rilldata.com as that would be actually used as CDN.

**Comment by magorlick** [comment]
@gorillio-ops , @godzig 

None of the requests in this branch have any connection to changing the links, files, or upload process for the binaries,  only the release notes and associated video and image assets.

I don't mind the current link address - we need to manually cut the right assets and upload somewhere we host. Github and docusaurus both have their rough edges. I can't think of a way to automate this part it will always be a manual step as we create the right walkthrough videos to include.  

@godzig , how are we using vimeo today and why aren't any of the links we added to the release notes here leveraging that step - or is this that code that we put after the gif?  Is all of this captured in our run book?

@gorillio-ops , are you updating our release run book as you make changes to our process or is this something we need to connect on?

**Review by nishantmonu51 — APPROVED** [review]
LGTM

**Comment by godzig** [comment]
> @godzig , how are we using vimeo today and why aren't any of the links we added to the release notes here leveraging that step - or is this that code that we put after the gif? Is all of this captured in our run book?

The links are there only as Vimeo `VideoIDs`; the url is built during compile for docusaurus using the title value of the markdown link or file attachment. 

An mp4 or gif that includes a VimeoID markdown title will render on the live site as an embedded Vimeo video while also rendering on github as a gh-hosted gif or mp4. Details on how to achieve this are [outlined in the runbook](https://www.notion.so/rilldata/Release-Run-Book-20a4afb8f2f64d06814a0c89d51bfdcf#9cfcef4799c845b5ad76a32413dd7112), and in the [original pull request](https://github.com/rilldata/rill-developer/pull/615).

**Comment by begelundmuller** [comment]
Text looks good to me. Hopefully we can update the install instructions with the curl script infra is putting together before releasing.

**Review by begelundmuller — APPROVED** [review]

**Pull request merged**
