### PR TITLE
Source to dashboard quick-start

### LINKED ISSUE #633: Short Circuit: If a source has a timestamp column, create functionality to go directly to dashboard
In the case where a model has a timestamp column already, we can easily use the "quick start" functionality to get the user to a dashboard in one click.

To close this out:
- [ ] figure out _where_ this functionality should go, and mock it up somehow.
- [ ] implement

### PR DESCRIPTION
**Pull request by AdityaHegde**
Closes #633 

Adding a button to quick-start a dashboard for sources.
- Adding a menu item beside any source with timestamp column.
Screenshot 2022-07-25 at 5 44 41 PM
- Adding a button in onboarding to quick start for imported sources with timestamp column.
Screenshot 2022-07-25 at 5 48 53 PM

Adding an async method (will be async thunk once Source is moved to its slice) that,
- Creates a model with `select * from <>`
- Creates a metrics definition with the modelId from ^ and the 1st timestamp column.
- Auto populates measure and dimensions using existing action for this.
- Focuses the newly created dashboard

There will be an overlay until dashboard is created.
Screenshot 2022-07-25 at 5 49 07 PM

### CODE REVIEW

**Comment by hamilton** [comment]
@AdityaHegde thanks for filing ~ at a high level this looks good. Marissa is thinking through the actual UX we want. Let's circle back on this PR in a day or two once we have a better idea about how to tweak the UX.

It's pretty neat going directly to a dashboard :)

**Comment by magorlick** [comment]
@AdityaHegde , thanks for this PR!  A few changes requested around the UX:

**Three Dot Menu for Sources**
- Remove the repetitive name of the asset from the menu.   
- Maintain styling highlight on the asset when using the three dot menu .
- Change Labels for menu:
    - quick dashboard
    - new model
    - rename
    - delete
- Always present all labels
  - Grey out “quick dashboard” if they are missing 1 DIMENSION or a time series.
  - Users can’t interact with  greyed out “quick dashboard” options.
  -  If the option is grey, we should provide subtext justified to the right to let them know what they need to do to make a valid dashboard. (eg: _”create time series”; “create dimension”_)

**Onboarding**
Please remove the CTA buttons directing people to the dashboard on the Getting Started screen for now.

**Comment by AdityaHegde** [comment]
@magorlick Talked to @hamilton . I have removed the changes to onboarding. He will fix the rest of the UX issues.

**Review by hamilton — CHANGES_REQUESTED** [review]
had a couple of code changes @AdityaHegde, mostly around naming. let me know what you think

**Review by hamilton — APPROVED** [review]
awaiting feedback from @magorlick

**Comment by magorlick** [comment]
This UI feels like a really nice update to the menu.  No changes.  Thanks!

**Pull request merged**
