### PR TITLE
adds in error handling for other pages

### LINKED ISSUE #966: Routing Error Feedback on Sources and Models
**Issue**
Is it possible to extend this UI to the sources and models workspaces when there is an error.

**Importance**
It should be clear to users that something has gone wrong and they need to try something new to restore functionality to the application.

**Definition of Done**
Routing error messages are presented to users for all asset screens.

**Additional Context**
https://github.com/rilldata/rill-developer/pull/951

### PR DESCRIPTION
**Pull request by hamilton**
closes #966 

It would be very much worth checking this in a built version as well. This effectively will delay serving the page endpoint to the page until we've got access to the store client-side. It's a hack until we've migrated away from our current state management model. Seems to work!

### CODE REVIEW

**Comment by magorlick** [comment]
Something isn't quite right with this branch. I get an error when I try to build and CI is failing.

```
src/lib/util/entity-exists.ts:16:17 - error TS2339: Property 'entities' does not exist on type 'unknown'.

16     get(store)?.entities?.some((entity) => entity.id === id) || false;
                   ~~~~~~~~


Found 1 error in src/lib/util/entity-exists.ts:16

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @rilldata/rill@0.11.0 
npm ERR!   at location: /Users/marissagorlick/Documents/rilldata/rill-developer/web-local 
```

**Comment by ericpgreen2** [comment]
`+page.ts` is run on both server and client. Maybe that's the source of the build error?

**Comment by hamilton** [comment]
ah, for some reason I thought I had controlled for that. We need to check if the browser is running first. I'll circle back and figure that out next week when I"m back online.

**Comment by hamilton** [comment]
Actually, this is not because something runs on the server. This is just a typescript error. Easy fix

**Comment by hamilton** [comment]
@ericpgreen2 @magorlick ready for another review.

**Review by magorlick — APPROVED** [review]
lgtm

**Review by ericpgreen2 — APPROVED** [review]
Code looks good 👍

**Review by magorlick — APPROVED** [review]
lgtm

**Pull request merged**
