### PR TITLE
handle more sql node types

### PR DESCRIPTION
**Pull request by pjain1**
Date functions with casts are now supported with protobuf.

### CODE REVIEW

**Review by begelundmuller — APPROVED** [review]
This looks good to me. Should we have some some test cases for this?

**Comment by pjain1** [comment]
Test cases for protobuf serialization are missing in general, can it be done in another PR ?

**Review by nishantmonu51 — APPROVED** [review]
👍

**Review by nishantmonu51 — APPROVED** [review]
LGTM.

**Pull request merged**
