### PR TITLE
Add remote sources

### PR DESCRIPTION
**Pull request by ericpgreen2**
TODOs

P0
- [x] Broken CSVs crash the runtime (@begelundmuller) – it's a DuckDB issue, see: https://github.com/duckdb/duckdb/issues/5077
- [x] User-facing error messages. See Marissa's list below. Short-term approach: frontend will do regex to catch the most common errors. (@ericpgreen2)
- [x] Fix dialog height (@ericpgreen2)
- [x] The import table CLI command / `ImportTableCommand` should go through the runtime (@AdityaHegde)
- [x] The `drop-source` CLI command should go through the Runtime's drop command (@AdityaHegde)
- [x] Better sidebar UX for source creates/renames/deletes. 
- [x] Finalize documentation (@ericpgreen2, @magorlick)
- [x] Update links in copy to reflect docs (@ericpgreen2)
- [x] Fix failing tests (@AdityaHegde)
- [x] Update version of embedded runtime
- [ ] Cancel / replace / "keep both" modal when creating a remote source w/ a taken name (@ericpgreen2)
- [ ] Sometimes, it appears like an import fails completely. Hard to reproduce. (@AdityaHegde)

P1
- [ ] Pressing `enter` in the GCS/AWS sources form takes you to documentation, rather than submitting form 
- [ ] Change "refresh" button for local sources to be "re-upload" file

Future
- Support gzipped files (not a blocker for `0.13.0` but very important) (@AdityaHegde)
- Support glob patterns (not a blocker for `0.13.0` but very important) (@AdityaHegde)
- Add a "Refresh All Remote Sources" button
- The refresh icon should spin or morph into the status active icon in interface
- Connect the dots between last import date and the last date in the timeseries.
- Add remote sources from the CLI.
- "Preflight": validate credentials, return a data preview, detect schema _before_ a user submits the form

### CODE REVIEW

**Comment by magorlick** [comment]
Thank you for your hard work on this feature @ericpgreen2 ! I am excited to have the back end in place so I can really kick the tires, but I promised an experience check today to help guide your work until I return on Tuesday. TLDR, let's make sure the sources ingestion fields are incredibly clear, probably through tool tips and documentation, so it feels dead simple to fill out the form once you open the modal.

**Remote Sources Overall**
The input values are being carried across Remote sources inputs when you navigate across them (S3, GCS, https) and should not be. They should be sticky within each source only for that session.

Why is there a place to enter a region? I remember buckets being assigned to a region when they are created. Can we auto-detect this? If not, we should provide clarity into how they can figure this out and enter the correct region. A drop down might even make sense since they are a set number of possible values.  If we don't need it, we shouldn't ask for it.  Can you please add a tool tip or a place for a note on what to expect here.

I can't tell from the UI that I can't pick up nested buckets and I need to reference 1 specific file.  Can you please add a tool tip or a place for a note on what to expect here.

I can't tell what file formats will work in remote sources.  Can you please add a tool tip or a place for a note on what to expect here.

Sampling is not in scope for this release, but it will be in the near future.  When we get there I will want to know what our sampling method is while sampling 1M rows? A tool tip would be helpful.

We should provide links to the documentation to help people locate their Access Key ID. Secret access key and Session token. You did this for GCS, which was helpful, but I wonder if custom docs in our own docs that focus on this task and point out to GCS and S3 docs would be better. I would like to try these documented flows once we have a backend connected to make sure it is clear to our users.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

**Local source**
The button doesn't work. Does this depend on the new back end? Let's make sure we don't lose this functionality. Should we enable drag and drop when this modal is up? It doesn't work right now when the data ingestion modal is present.

**Example source**
This is out of scope for the 0.12 release. Please remove the menu item.

**Application Nav and Inspector**
After ingesting a file on this branch with drag and drop, I am not seeing any insights in the upper right hand corner letting me know the last time that the file was ingested or a refresh button. I do see the refresh button in the menu in the left nav bar, but nothing seems to happen when I select it.

**Comment by ericpgreen2** [comment]
Thanks for the good feedback, @magorlick!

- **Copy clarity**: I've updated the copy, added a link for AWS access keys, and added a tooltip for URLs. Let me know if it's still not clear enough. You're right, we might want a dedicated docs page for connecting to data sources.
- **Functionality**: Yep, we haven't wired up some of these buttons (including the local source ingestion) to the backend yet.
- **Bucket regions**:  Yes, a bucket is assigned to a region, but the region isn't stated in the URL so the user does have to provide it separately. I'm following DuckDB's docs: https://duckdb.org/docs/guides/import/s3_import

**Comment by magorlick** [comment]
Thank you for these changes @ericpgreen2 !  I think these are nice improvements to help the clarity of our form for source ingestion.  A few notes:

P0. As we discussed today, let's make sure we get a page in our documentation for the release of this feature. It doesn't have to be super detailed, but I still think some prose that helps people with different levels of experience doing this be successful is important.  Once the documentation is in place, I think we should change the links to external documentation to our own docs.  Our docs should link out to third party tools. This will help SEO and help us understand how many people are seeking more help.

P0. You made a nice info tool tip for the URL, but I am not sure that the copy is quite right. Hard to tell without the back end, but glob URLs are out of scope for V1 of the sources functionality.  If it is possible in this release, we have more to think about around how the data lands in a source and how we communicate that. Please let me know what is planned for the back end so we can figure out how to proceed.  We should consider adding these to all of the form inputs.  Let's chat about copy tomorrow.
image

P0. I can't tell what the form auto-fill experience will be like once we have the backend in place.  I will want to review everything again once we are wired up tomorrow and step through your documentation with my internal example.  Please ping me when you are ready!

**Comment by ericpgreen2** [comment]
@magorlick,
- **Docs:**  Yes, I did add a docs page! You can check it out by running `npm run dev` from the `/docs` directory. Let's discuss the content of the docs page tomorrow. Ideally, I think it'd be nice if the user could get directly to the {GCP, AWS} access key instructions from the Rill app, and not have to click into the Rill docs first, but we can discuss.
- **Tooltip:** Agreed. I actually put that note about glob patterns in as somewhat of an optimistic placeholder. Waiting to see what we're able to accomplish on the backend, and what the constraints are, before finalizing.

**Comment by magorlick** [comment]
Thanks for clarifying on the docs - I was looking on the other 2 branches you shared for docs changes for this markdown and I didn't see it.  I will look at this branch for the documentation and sync with you on the tool tips by EOW.

**Comment by magorlick** [comment]
@ericpgreen2 , thank you for your hard work on this feature. It was great to see all three connectors working and I recreated much of my KPI report! Here on my notes on experience polish, I think it would be fantastic if we could get all of the P0 notes and as many of the P1 notes as we could in before release.

**Overall**
- P0: The CLI commands do not work for importing source parquet files.
- P0: Refresh All Sources button would make this much more functional for real work with many data sets. I thinik this is essential to make this feel great.
- P0: The inputs are pushed down outside of the modal when there is a validation error.  
- P1: We should grey out the "Add Source" CTA button when the form is not valid.
- P1: *"Add source"* call to action for the source import modal should be Title Case as seen across the rest of the application.
- P1: messages when renaming says it is reimporting and is confusing.
- P1: [ERROR] The error message for existing tables should be user-facing. It should be possible to replace sources. 
- P1: [ERROR] When my remote csv file has an ingestion error the inerface stops working with no feedback.
- P1: [ERROR] Confusing error when you try to import a .gz file.
- P1: [ERROR]  when I do not enter my credentials I dont get a human readable error message.  
- P2: Would be nice to connect the dots between last import date and the last date in the timeseries.
- P2: I would like to be able to do this from the CLI.

**GCS**
- P0: Shorten the text at the top to read *"Connect to Google Cloud Storage"*
- P0: I don't think we support glob patterns from what I tried.  Please change the tool tip info copy for the GS URI.
	*- "The Google Cloud Storage URI (`gsutil URI`) for one CSV or Parquet file. We do not support multi-file data ingestion."*
- P0: Add an field at the bottom called "Credentials" that indicates 1) that it is optional and 2) that it is detecting local credentials with a success indicator if they were found and a warning if they could not be found. 
	- Move the info text from the top to the "Credientials" info tool tip.
		- *"For private buckets, first set your application default credentials (link to our internal documentation in the GCS auth instructions), which Rill will detect and use for authentication. One way to set these credentials is by running this CLI command: `gcloud auth application-default login`."*
- P0: I was not able to get a privately stored GCS file to import into Rill, but I dont think I had access to a valid private file.  This needs validation before shipping.

**S3**
- P0: Shorten the text at the top to read *"Connect to AWS S3 Storage."*
- P0: Rill should be picking up env credentials. It a bad user experience to have to put them in repeatedly for each source. If I must put my credentials in here manually, I expect the characters to be obscured as they are entered in for security. Is the expectation that I would enter these in every time I need to refresh? How would I update them if they are stored in the application? Security concerns?
- P0: add an info tool tip for credentials
	- *"For private buckets, create an access key and access secret credentials (link to our internal documentation in the AWS auth instructions), which Rill use for authentication. One way to set these credentials is by running this CLI command: `aws iam create-access-key`."*

**Local**
- Add text at the top to read *"Import Locally Stored File."*
- Clicking on *"Local"* should immedidatly pop up a system dialog to find the file without an interstitial button.  The user should have the chance to name the rename the source and before selecting "Add source".

**Documentation**
- I did an overhaul of the documentation to better step through all of the methods for data ingestion in a focused way on another branch and tagged you as the reviewer.

**Review by hamilton — APPROVED** [review]

**Pull request merged**
