### PR TITLE
Guess the OS & decorate tabs

### PR DESCRIPTION
**Pull request by godzig**
Cleaning up the binary install page with tabs and OS guesses based on browser UA. 

https://www.loom.com/share/0adb8e1ca7664933a684c1591acc90e5

### CODE REVIEW

**Comment by bcolloran** [comment]
@godzig -- mike I reviewed this a moment ago and I think the tabbed view looks great-- nice usability/readability improvement. I'm guessing you have more pressing matters to attend to than this in the next couple days, but other than updating this to reflect the latest install instructions (`curl` etc), was there anything else you had wanted to do or other notes to pass on to someone else to get this over the line?
(cc  @magorlick )

**Comment by godzig** [comment]
I had tried to also work in a rudimentary "guess at the OS" as part of this, but never worked out the kinks. Alas...

**Review by bcolloran — APPROVED** [review]
hey @magorlick I'm approving these docs changes, I think we should merge. This just puts the per-platform binary download link and other platform specific info within a tabbed view. I think it's a bit better and looks cleaner, even though it will mean an extra click for some people, but it's a judgement call, so I'll leave it to you to merge if you like it.

**Comment by magorlick** [comment]
Yeah I think the curl script is the primary path now, but this is a nice feature. Let's merge.

**Pull request merged**
