### PR TITLE
Adding auto syncing of models to files

### PR DESCRIPTION
**Pull request by AdityaHegde**
- [x] Any model created and modified will be persisted to file system under `models/<modelName>.sql`.
- [x] Any direct updates to this model file will update the profiling (and errors) in the UI.
- [x] Adding a new model file in `models` creates a new model with that query and name.
- [x] Make sure models have unique names.
- [x] Store auto incremented model id in state.
- [x] Deleting/renaming the model file will delete/rename the model

### CODE REVIEW

**Review by hamilton — CHANGES_REQUESTED** [review]
Looks good.

**A few comments:**
- currently the editor does not update if I update a sql file. This is no fault of the PR; we'll need to have a separate issue to patch that for the time being

**A few improvements I am hoping we can make here:**
- it'd be good to explain in a comment what the repository pattern is. For those of us who come from a functional programming background, it might be confusing or unclear what the nomenclature means.
- if I delete a file in the filesystem, it doesn't delete it in the application state. I would expect the filesystem to be the source of truth, so if something disappears in the models folder, I would expect that it gets removed in the application state. Could we have this happen in this PR?
- if I rename the file in the filesystem, it would make sense in that case to just have it throw out any model that exists and create a new one, vs. renaming in the interface, which should rename the source file. That would match my expectation as a user.

Let me know what you think. I do see that you noted the renaming thing. What blocks doing that in this PR? Do you need help with the decision rules or is it a complexity thing?

**Comment by AdityaHegde** [comment]
Regarding delete, yes i was hesitant to delete the model when the file is deleted. I have special handling to recreate the file. I can switch over to deleting the model.

**Review by hamilton — CHANGES_REQUESTED** [review]
most recent change gives me the following error when I run `npm run server`

```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/entity-state-service/PersistentModelEntityService.ts:30:32
    at Array.forEach (<anonymous>)
    at PersistentModelEntityService.init (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/entity-state-service/PersistentModelEntityService.ts:29:31)
    at EntityStateSyncService.init (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/sync-service/EntityStateSyncService.ts:41:33)
    at async Promise.all (index 2)
    at DataModelerStateSyncService.init (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/sync-service/DataModelerStateSyncService.ts:36:9)
    at RillDeveloper.init (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/RillDeveloper.ts:35:9)
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/server/server.ts:14:5
[ERROR] 20:48:05 TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
```

**Review by hamilton — APPROVED** [review]

**Review by hamilton — CHANGES_REQUESTED** [review]
One more issue I found ~ if I add a non-sql file (e.g. a csv), I get an infinite loop of notifications like `Another model with the name whatever.csv already exists`

**Pull request merged**
