### PR TITLE
Fixing valid dashboard refresh

### PR DESCRIPTION
**Pull request by AdityaHegde**
We had a reactive statement dependant on `$runtime`. Since it changes every time jwt changes this lead to constant refresh of the dashboard.

### CODE REVIEW

**Comment by AdityaHegde** [comment]
All i am doing is not depending on the whole of `$runtime` here. This is essentially memoisation of host. The `runtime.set` is getting called since jwt refreshes. Which changes the contents of `$runtime`. Which triggers the reactive statement that refetches the queries.

Not sure I understand your concern here.

**Comment by AdityaHegde** [comment]
Ah its the race condition that is the problem. Lemme check

**Comment by ericpgreen2** [comment]
To go with your approach, but still avoid the race condition, maybe a `derived` store for the runtime host would work.

**Comment by ericpgreen2** [comment]
Alternatively, I _think_ making the `useProject` hook that's used on the dashboard page into a `useProjectDeploymentStatus` custom hook (w/ a selector for the status) would work & is a more correct use of TanStack.

**Comment by AdityaHegde** [comment]
Changing `useProject` should be in a different PR. It is unrelated. I have just removed the reactive statement. This assumed instanceId always changes when the deployment for a project changes.

**Review by ericpgreen2 — APPROVED** [review]

**Pull request merged**
