### PR TITLE
Remove unused vars

### PR DESCRIPTION
**Pull request by djbarnwal**
All the variables/methods which were declared but never used are deleted
All the variables/methods which were declared and are being used in commented code have been commente

### CODE REVIEW

**Review by bcolloran — CHANGES_REQUESTED** [review]
looks good @djbarnwal , thanks for doing this. If the lint rule is now passing, remember to delete the line `    "@typescript-eslint/no-unused-vars": "warn",` from `.eslintrc.cjs`

**Comment by djbarnwal** [comment]
@bcolloran There are still some vars present in the server layer which have to be removed. Also I think it would be better to wait out for the big PRs to be merged. Based on [this](https://github.com/rilldata/rill-developer/pull/403#issuecomment-1159035074) discussion, major PRs will have a lot of merge conflict if we merge this now. But if it makes more sense, then we can merge this now as well.

**Comment by ericpgreen2** [comment]
No major branches outstanding for me. Anyways, I don't think deleting unused variables should cause conflicts anywhere. I vote for merging it in.

**Comment by djbarnwal** [comment]
Closing in favor of  #445 as fork branches can't run CI jobs

**Pull request closed without merging**
